//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notes_Program.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notes
    {
        public int id { get; set; }
        public string Heading { get; set; }
        public string Text { get; set; }
    }
}
